server:
  port: 8081

spring:
  application:
    name: DOCTOR-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/db_docterservice
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 414963

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html





