spring:
  application:
    name: DocterService
  datasource:
    url: jdbc:postgresql://localhost:5432/db_docterservice
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Akhil429@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true





